#services:
#  department-service:
#    image: department-service:v1
#    ports:
#      - '${APP_PORT}:${APP_PORT}'
#    environment:
#      - APP_PORT=${APP_PORT}
#      - DB_URL=${DB_URL}
#      - DB_USERNAME=${DB_USERNAME}
#      - DB_PASSWORD=${DB_PASSWORD}
#    restart: always
#
#version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice
    ports:
      - '3306:3306'
    volumes:
      - ./microservice.sql:/docker-entrypoint-initdb.d/microservice.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s
      start_period: 30s

  department-service:
    image: department-service:v1
    container_name: department-service
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - APP_PORT=${APP_PORT}
      - DB_URL=jdbc:mysql://mysql-db:3306/microservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: always

volumes:
  mysql-data:

version: '3.8'