apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service
  template:
    metadata:
      labels:
        app: department-service
    spec:
      containers:
        - name: department-service
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: Never
          ports:
            - containerPort: ${APP_PORT}
          envFrom:
            - secretRef:
                name: department-service-secret