apiVersion: v1
kind: Service
metadata:
  name: department-service
spec:
  type: NodePort
  selector:
    app: department-service
  ports:
    - port: ${APP_PORT}
      targetPort: ${APP_PORT}
      nodePort: 30082